#!/bin/bash
echo "This execution puts myip into /usr/local/bin so you can use it in your path"
cp myip /usr/local/bin/myip
chmod +x /usr/local/bin/myip
echo "Done. Now, type myip so you can check your external IP from the console"
